# Generated by Django 5.2.3 on 2025-06-12 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='Full Name')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='Objectives')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['fullName'],
            },
        ),
    ]
